AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TinyURL - SAM stack (Hello + Create + Redirect + DynamoDB)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 256
    Architectures: [ arm64 ]
  Api:
    # StageName burada desteklenmez; implicit API için varsayılan "Prod" kullanılır
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"

Resources:
  UrlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: url-mappings
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: shortCode
          AttributeType: S
      KeySchema:
        - AttributeName: shortCode
          KeyType: HASH

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Events:
        GetHello:
          Type: Api
          Properties:
            Path: /hello
            Method: GET

  CreateUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_url/
      Handler: app.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: !Ref UrlTable
          BASE_URL: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlTable
      Events:
        PostUrl:
          Type: Api
          Properties:
            Path: /url
            Method: POST

  RedirectUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: redirect_url/
      Handler: app.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: !Ref UrlTable
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlTable
      Events:
        GetShort:
          Type: Api
          Properties:
            Path: /{shortCode}
            Method: GET

Outputs:
  HelloApiUrl:
    Description: Invoke URL for GET /hello
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"

  UrlApiBase:
    Description: Base URL for TinyURL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
