AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Milestone 1 – Hello World (SAM + API Gateway)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 5
    MemorySize: 128
    Architectures:
      - x86_64

Resources:
  HelloApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GetHello:
          Type: Api
          Properties:
            Path: /hello
            Method: get
