AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TinyURL - SAM stack (Hello + Create + Redirect) - implicit API

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 256
    Architectures: [ arm64 ]
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"

Resources:
  # --- Hello (test) ---
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Events:
        GetHello:
          Type: Api
          Properties:
            Path: /hello
            Method: GET

  # --- Create URL ---
  CreateUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_url/
      Handler: app.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: url-mappings
          # ADDED: Tam kısa URL döndürmek için Base URL
          BASE_URL: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
          # (Opsiyonel) Redis/S3 – şimdi boş bırak, sonra doldurabilirsin
          # REDIS_HOST: ""
          # REDIS_PORT: "6379"
          # CACHE_TTL_SEC: "86400"
          # ARCHIVE_BUCKET: ""
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: url-mappings
      Events:
        PostUrl:
          Type: Api
          Properties:
            Path: /url
            Method: POST

  # --- Redirect URL ---
  RedirectUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: redirect_url/
      Handler: app.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: url-mappings
          # (Opsiyonel) Redis/S3 – ileride kullanmak üzere
          # REDIS_HOST: ""
          # REDIS_PORT: "6379"
          # CACHE_TTL_SEC: "86400"
          # ARCHIVE_BUCKET: ""
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: url-mappings
      Events:
        GetShort:
          Type: Api
          Properties:
            Path: /{shortCode}
            Method: GET

  # --- CloudWatch Log Retention (ADDED) ---
  CreateUrlLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CreateUrlFunction}"
      RetentionInDays: 14
  RedirectUrlLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${RedirectUrlFunction}"
      RetentionInDays: 14
  HelloLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${HelloWorldFunction}"
      RetentionInDays: 14

Outputs:
  # Var olanlar
  HelloApiUrl:
    Description: Invoke URL for GET /hello
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"

  UrlApiBase:
    Description: Base URL for TinyURL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  # ADDED: ekstra çıktı bilgileri
  ApiId:
    Description: API Gateway RestApi Id
    Value: !Ref ServerlessRestApi
  CreateUrlFunctionArn:
    Description: Create URL Lambda ARN
    Value: !GetAtt CreateUrlFunction.Arn
  RedirectUrlFunctionArn:
    Description: Redirect URL Lambda ARN
    Value: !GetAtt RedirectUrlFunction.Arn
