name: Deploy SAM (Milestone 1)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SAM Build (app)
        working-directory: sam-app
        run: sam build

      - name: SAM Deploy (app)
        working-directory: sam-app
        run: |
          sam deploy \
            --stack-name tinyurl-app \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM \
            --region ${{ secrets.AWS_REGION }}

      - name: Show API URL Output
        run: |
          aws cloudformation describe-stacks \
            --stack-name tinyurl-app \
            --region ${{ secrets.AWS_REGION }} \
            --query "Stacks[0].Outputs" \
            --output table || true
